CREATE TABLE `TESTS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `TEST_NAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `QUESTIONS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `QUESTION` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `ANSWERS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `ANSWER` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `ANSWERS_TO_QUESTIONS` (
    `ANSWER_ID` INT NOT NULL,
    `QUESTION_ID` INT NOT NULL,
    PRIMARY KEY (`QUESTION_ID`, `ANSWER_ID`),
    FOREIGN KEY (`ANSWER_ID`) REFERENCES `ANSWERS` (`ID`),
    FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTIONS` (`ID`)
);
;

CREATE TABLE `CORRECT_ANSWERS_TO_QUESTION` (
    `ANSWER_ID` INT NOT NULL,
    `QUESTION_ID` INT NOT NULL,
    PRIMARY KEY (`QUESTION_ID`, `ANSWER_ID`),
    FOREIGN KEY (`ANSWER_ID`) REFERENCES `ANSWERS` (`ID`),
    FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTIONS` (`ID`)
);

CREATE TABLE `QUESTIONS_TO_TESTS` (
    `QUESTION_ID` INT NOT NULL,
    `TEST_ID` INT NOT NULL,
    PRIMARY KEY (`QUESTION_ID`, `TEST_ID`),
    FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTIONS` (`ID`),
    FOREIGN KEY (`ANSWER_ID`) REFERENCES `ANSWERS` (`ID`)
);
